name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]  # macos-13 for better compatibility
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    
    - name: Build development shell
      run: nix develop --command echo "Development environment ready"
    
    - name: Run tests
      run: nix develop --command ./grimoire test